### ISSUE TITLE
Привести код согласно Style Guide for Python Code

### ISSUE THREAD

**Issue by sp1ker** [Alex020202/my_game#1]
Сам стайлгайд тут - https://www.python.org/dev/peps/pep-0008/

По возможности используй IDE, например, JetBrains PyCharm Community Edition. Там можно настроить автоформатирование.
Самое проблемное у тебя даже не пробелы всякие, а именование переменных, названий классов, их свойств и методов. Всё время меняешь стиль написания.

**Comment by Alex020202** [comment]
по сути, сделал

**Comment by alexander-deb** [comment]
> Сам стайлгайд тут - https://www.python.org/dev/peps/pep-0008/
> 
> По возможности используй IDE, например, JetBrains PyCharm Community Edition. Там можно настроить автоформатирование.
> Самое проблемное у тебя даже не пробелы всякие, а именование переменных, названий классов, их свойств и методов. Всё время меняешь стиль написания.
по сути сделал

**Comment by sp1ker** [comment]
https://github.com/Alex020202/my_game/blob/f491350b1a7d2a252ffa090f945d6724ee019bac/src/Block.py#L10

**Comment by alexander-deb** [comment]
теперь все нормально)
