### ISSUE TITLE
Вынести определение движения

### ISSUE THREAD

**Issue by sp1ker** [Alex020202/my_game#10]
https://github.com/Alex020202/my_game/blob/f491350b1a7d2a252ffa090f945d6724ee019bac/src/Game.py#L98-L117

Это можно перенести в класс `Hero`. Назови метод как-нибудь типа `move`. Метод принимает на вход keys - нажатые клавиши

**Comment by alexander-deb** [comment]
забыл обозвать последний коммит. смотри
