### ISSUE TITLE
Дублирование логики

### ISSUE THREAD

**Issue by sp1ker** [Alex020202/my_game#12]
https://github.com/Alex020202/my_game/blob/d4879c8ac53b2812a59be4b8756619984fd38146/src/Hero.py#L105

Не надо дублировать логику расчёта

**Comment by alexander-deb** [comment]
где там дублирование? или ты имеешь ввиду, чтобы  заменил y - vel. на next_position?

**Comment by sp1ker** [comment]
https://github.com/Alex020202/my_game/blob/bbcd7a4b8a9cc985270e6b24f1816118c8634280/src/Hero.py#L34
https://github.com/Alex020202/my_game/blob/bbcd7a4b8a9cc985270e6b24f1816118c8634280/src/Hero.py#L99

**Comment by alexander-deb** [comment]
это же не дублирование. первый раз при создании класса, второй после каждой итерации меняет значения. если я оставлю только второй, пайчарм любезно попросит закинуть это в _инит_

**Comment by sp1ker** [comment]
Дублирование в чистом виде. 2 одинаковые формулы. Вынеси в метод и вызывай в 2 местах.

**Comment by alexander-deb** [comment]
ну у меня 4 переменные в этой функции. и они все дублируются в ините и в функции, которая их вычисляет, проще эту функцию вызвать в ините, чтобы не создавать 4 новые, которые вместе будут делать то, что делает одна change_variables. но тогда пайчарм скажет, что это помарка, что переменные с параметром self не занесены в инит. Так можно сделать, но я их туда добавил, потому что пойчарм ворчал

**Comment by alexander-deb** [comment]
я сделал без дублирования, потом закоммичу
