### ISSUE TITLE
Перенести это в класс Game

### ISSUE THREAD

**Issue by sp1ker** [Alex020202/my_game#14]
https://github.com/Alex020202/my_game/blob/bbcd7a4b8a9cc985270e6b24f1816118c8634280/src/Hero.py#L89
Этого тут не должно быть. Почему персонаж может остановить игру? У него есть такие полномочия разве?
Вся функция сводится к тому, чтобы вычислить следующую координату персонажа. О том, что это конец экрана и пора заканчивать игру - знает только игра.
Т.е. следующее условие (не код внутри, а само условие остановки игры) должно быть в логике игры, а не персонажа
https://github.com/Alex020202/my_game/blob/bbcd7a4b8a9cc985270e6b24f1816118c8634280/src/Hero.py#L81

**Comment by sp1ker** [comment]
что-то типа:
```python
if Hero.next_legs_position >= 512:
   self.is_running = False

**Comment by alexander-deb** [comment]
тут всё
