### ISSUE TITLE
Рефакторинг, часть 1

### ISSUE THREAD

**Issue by sp1ker** [Alex020202/my_game#4]
Создай класс `Game` и вынеси туда то, что относится к самой игре целиком. Для начала это `game_over` и `play_music`. А так же создай метод run, который будет содержать основной цикл игры.

В game.py в идеале должен быть только вызов `run` конфиг, который передастся в конструктор класса `Game`. Это пока можешь не делать, если не осилишь. Достаточно выполнить предыдущий абзац

**Comment by Alex020202** [comment]
не доделал до конца... без джетпака все хорошо работает

**Comment by alexander-deb** [comment]
не доделал до конца... без джетпака все хорошо работает

**Comment by sp1ker** [comment]
Вынеси Game в отдельный файл

**Comment by sp1ker** [comment]
Чтобы было удобней, переименую главный файл из game.py в app.py, а Game убери в src/Game.py

**Comment by sp1ker** [comment]
> не доделал до конца... без джетпака все хорошо работает

Пока забей на джетпак. Можешь пока его вообще не использовать

**Comment by alexander-deb** [comment]
сделал, джетпак работает, изменил еще анимацию падения
