### ISSUE TITLE
Условные переменные лучше называть с префикса is

### ISSUE THREAD

**Issue by sp1ker** [Alex020202/my_game#6]
https://github.com/Alex020202/my_game/blob/6690dce1ad68a1b5dcd4d7c8e2eebdea857768c9/game.py#L180
`run` - это действие. А у тебя условие, что игра запущена. Такую переменную/свойство лучше назвать `isRunning`.

Из-за того, что `run` занято, ты не смог создать метод `run`, а создал `run_game`. Вообще называть так методы не стоит, т.к. мы и так находимся в классе `Game`, а значит `run` относится напрямую к нему.

**Comment by alexander-deb** [comment]
сделал
