### ISSUE TITLE
Исключить служебную папку .idea из гита

### ISSUE THREAD

**Issue by sp1ker** [Alex020202/my_game#9]
добавить в корень проекта файл `.gitignore`.
добавить там 1 строчку:
```
.idea
```

Не забыть сделать коммит!

**Comment by alexander-deb** [comment]
сделал
что это дает?

**Comment by sp1ker** [comment]
У тебя есть папка .idea в корне проекта. Эта папка должна игнорироваться в git. Для этого и добавили её в гит-игнор. И.е. для гитары эта папка не существует

**Comment by sp1ker** [comment]
Что ещё за game.gitignore?) Нужно без game

**Comment by alexander-deb** [comment]
+
